fxtypes =  
{
	 
	{
		effect = "root",
		fx =  
		{
			properties =  
			{
				property_00 =  
				{
					name = "Radius",
					type = "VARTYPE_ARRAY_TIMEFLOAT",
					value =  
					{
						0,
						6,
						1,
						6,
					},
				},
				property_01 =  
				{
					name = "Attenuation",
					type = "VARTYPE_ARRAY_TIMEFLOAT",
					value =  
					{
						0,
						2.06000,
						1,
						2.06000,
					},
				},
				property_02 =  
				{
					name = "Colour",
					type = "VARTYPE_ARRAY_TIMECOLOUR",
					value =  
					{
						entry_00 =  
						{
							0,
							255,
							247,
							197,
							255,
						},
						entry_01 =  
						{
							0.01961,
							255,
							118,
							33,
							255,
						},
						entry_02 =  
						{
							0.04793,
							255,
							234,
							139,
							255,
						},
						entry_03 =  
						{
							0.07516,
							255,
							107,
							16,
							255,
						},
						entry_04 =  
						{
							0.10675,
							245,
							255,
							192,
							255,
						},
						entry_05 =  
						{
							0.14270,
							255,
							113,
							26,
							255,
						},
						entry_06 =  
						{
							0.18627,
							255,
							235,
							199,
							255,
						},
						entry_07 =  
						{
							0.22549,
							255,
							125,
							41,
							255,
						},
						entry_08 =  
						{
							0.26471,
							255,
							241,
							206,
							255,
						},
						entry_09 =  
						{
							0.30828,
							255,
							76,
							26,
							255,
						},
						entry_10 =  
						{
							0.35839,
							255,
							234,
							182,
							255,
						},
						entry_11 =  
						{
							0.40087,
							255,
							176,
							57,
							255,
						},
						entry_12 =  
						{
							0.45752,
							255,
							230,
							151,
							255,
						},
						entry_13 =  
						{
							0.49237,
							255,
							76,
							26,
							255,
						},
						entry_14 =  
						{
							0.53486,
							255,
							199,
							129,
							255,
						},
						entry_15 =  
						{
							0.58824,
							255,
							99,
							24,
							255,
						},
						entry_16 =  
						{
							0.62527,
							255,
							211,
							143,
							255,
						},
						entry_17 =  
						{
							0.68083,
							255,
							98,
							21,
							255,
						},
						entry_18 =  
						{
							0.72549,
							255,
							223,
							158,
							255,
						},
						entry_19 =  
						{
							0.77560,
							255,
							78,
							12,
							255,
						},
						entry_20 =  
						{
							0.82898,
							255,
							242,
							184,
							255,
						},
						entry_21 =  
						{
							0.88344,
							255,
							153,
							31,
							255,
						},
						entry_22 =  
						{
							0.92593,
							255,
							246,
							193,
							255,
						},
						entry_23 =  
						{
							0.96950,
							255,
							126,
							26,
							255,
						},
						entry_24 =  
						{
							1,
							255,
							247,
							197,
							255,
						},
					},
				},
				property_03 =  
				{
					name = "Offset",
					type = "VARTYPE_ARRAY_TIMEVECTOR3",
					value =  
					{
						entry_00 =  
						{
							0,
							0,
							0,
							0,
						},
						entry_01 =  
						{
							1,
							0,
							0,
							0,
						},
					},
				},
				property_04 =  
				{
					name = "Loop",
					type = "VARTYPE_BOOL",
					value = 1,
				},
				property_05 =  
				{
					name = "Duration",
					type = "VARTYPE_FLOAT",
					value = 3,
				},
				property_06 =  
				{
					name = "Detail_From",
					type = "VARTYPE_FLOAT",
					value = 0,
				},
				property_07 =  
				{
					name = "Detail_To",
					type = "VARTYPE_FLOAT",
					value = 1,
				},
			},
			style = "STYLE_LIGHT",
		},
	},
}

